import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';

/* The static pages, policed the way the shell already is.
 *
 * `test/dead-class.test.js` says so in its own scope note: it covers only the
 * shell (`index.html` + `app/*.js`) against the three sheets it links, and
 * `about.html` and the roster-size pages "carry their own inline <style> and
 * were swept by hand". `test/dead-id.test.js` is narrower still -- its
 * `MARKUP` list is `['app/index.html']` for the reader and duplicate checks,
 * and only the two cross-reference tests at its foot look at every page.
 *
 * So the seven static pages had no standing guard at all: 89 class names and
 * a ~900-line inline stylesheet on `about.html`, plus six generated pages,
 * none of them checked in either direction. `about.html` has since gained a
 * section index carrying three new class names and nine new ids, which is
 * exactly the shape of addition a hand sweep stops noticing.
 *
 * Three directions, because a self-contained page can rot in three ways:
 *   1. a class in the markup with no rule anywhere the page loads -- the
 *      invisible-element bug `dead-class.test.js` exists for;
 *   2. a rule in the page's OWN inline sheet that nothing on the page wears
 *      -- dead CSS, which the shell's guard cannot check because its sheets
 *      are shared and it only scans the emission direction;
 *   3. an `id` declared and never read on its own page, or declared twice.
 *
 * Scope note that matters for direction 2: only the page's inline `<style>`
 * is checked for dead rules. `tokens.css` and `card.css` are shared, so a
 * rule in them is somebody else's to justify.
 *
 * The six chart pages are GENERATED by `scripts/charts.mjs` -- if this test
 * goes red on one of them it will be red on all six, and the fix belongs in
 * the template, never in the generated file.
 */

const ROOT = new URL('../app/', import.meta.url);
const read = (f) => readFileSync(new URL(f, ROOT), 'utf8');
const PAGES = readdirSync(ROOT).filter((f) => f.endsWith('.html') && f !== 'index.html');

/* Names that are real and rule-less, or ruled and unworn, on purpose. Each
 * needs a reason on the line, or the next sweep cannot tell a hook from a
 * leftover. Empty today, and that is the finding. */
const KEEP_CLASS = new Set([]);
const KEEP_ID = new Set([]);

/* Comments, `<style>` and `<script>` are not markup: a `class="..."` inside a
 * comment is prose about the page, not an element on it. */
const markupOnly = (html) => html
  .replace(/<!--[\s\S]*?-->/g, ' ')
  .replace(/<style[^>]*>[\s\S]*?<\/style>/g, ' ')
  .replace(/<script[\s\S]*?<\/script>/g, ' ');

const classesIn = (markup) => {
  const set = new Set();
  for (const m of markup.matchAll(/\bclass\s*=\s*["']([^"']*)["']/g)) {
    for (const c of m[1].split(/\s+/)) if (c) set.add(c);
  }
  return set;
};

const ruleNames = (css) => new Set(
  [...css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/\.(-?[a-zA-Z_][\w-]*)/g)].map((m) => m[1]));

const inlineCss = (html) =>
  [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map((m) => m[1]).join('\n');

const linkedCss = (html) =>
  [...html.matchAll(/<link[^>]*rel="stylesheet"[^>]*href="\.\/([^"]+)"/g)].map((m) => read(m[1]));

/* What the page's own scripts put on an element, or select by. JSON-LD is
 * data, not code. */
const scriptedClasses = (html) => {
  const set = new Set();
  const js = [...html.matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g)]
    .map((m) => m[1]).join('\n');
  for (const m of js.matchAll(/classList\.(?:add|remove|toggle|contains|replace)\(\s*["']([^"']+)["']/g)) set.add(m[1]);
  for (const m of js.matchAll(/className\s*\+?=\s*["']([^"']*)["']/g)) {
    for (const c of m[1].split(/\s+/)) if (c) set.add(c);
  }
  for (const m of js.matchAll(/["']\.([a-zA-Z_][\w-]*)["']/g)) set.add(m[1]);
  return set;
};

const idsIn = (html) => [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);

const bounded = (name) =>
  new RegExp(`(?<![A-Za-z0-9_$-])${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![A-Za-z0-9_$-])`, 'g');

test('every class in a static page\'s markup has a rule the page actually loads', () => {
  const orphans = [];
  for (const page of PAGES) {
    const html = read(page);
    const ruled = ruleNames([inlineCss(html), ...linkedCss(html)].join('\n'));
    for (const c of classesIn(markupOnly(html))) {
      if (!ruled.has(c) && !KEEP_CLASS.has(c)) orphans.push(`${page}: .${c}`);
    }
  }
  assert.deepEqual(orphans, [],
    'worn by an element and styled by nothing the page loads -- style it, '
    + 'delete it, or add it to KEEP_CLASS with the reason:\n  ' + orphans.join('\n  '));
});

test('every rule in a static page\'s own stylesheet is worn by something on it', () => {
  const dead = [];
  for (const page of PAGES) {
    const html = read(page);
    const worn = classesIn(markupOnly(html));
    const scripted = scriptedClasses(html);
    for (const c of ruleNames(inlineCss(html))) {
      if (!worn.has(c) && !scripted.has(c) && !KEEP_CLASS.has(c)) dead.push(`${page}: .${c}`);
    }
  }
  assert.deepEqual(dead, [],
    'a rule in the page\'s inline sheet that no element on the page wears:\n  ' + dead.join('\n  '));
});

test('every id on a static page is read on that page, and declared once', () => {
  const dead = [];
  const dupes = [];
  for (const page of PAGES) {
    const html = read(page);
    const ids = idsIn(html);
    for (const d of new Set(ids.filter((v, i) => ids.indexOf(v) !== i))) dupes.push(`${page}: #${d}`);
    /* A static page is self-contained: the reader has to be on the page --
     * an `href="#x"`, an `aria-labelledby`, its own script or its own sheet.
     * A module in `app/*.js` mentioning the same word is a coincidence, not a
     * reader, because none of these pages loads one. */
    for (const id of new Set(ids)) {
      if (KEEP_ID.has(id)) continue;
      const own = (html.match(bounded(id)) || []).length
        - (html.match(new RegExp(`\\sid="${id}"`, 'g')) || []).length;
      if (own <= 0) dead.push(`${page}: #${id}`);
    }
  }
  assert.deepEqual(dupes, [], 'declared twice on one page:\n  ' + dupes.join('\n  '));
  assert.deepEqual(dead, [],
    'declared and never read -- delete the attribute, and the element too if '
    + 'the id was its only reason to exist:\n  ' + dead.join('\n  '));
});

test('the sweep can see the pages it is pointed at', () => {
  // If these stop resolving, the three tests above are passing on an empty
  // set and the pages have gone unguarded again without going red.
  assert.ok(PAGES.includes('about.html'), 'about.html should be in scope');
  assert.equal(PAGES.filter((p) => /rotation-chart\.html$/.test(p)).length, 6,
    'all six generated roster-size pages should be in scope');
  const html = read('about.html');
  assert.ok(classesIn(markupOnly(html)).has('jumpto'), 'the section index is markup the scanner sees');
  assert.ok(ruleNames(inlineCss(html)).has('jumpto'), 'and its rule is in the inline sheet');
  assert.ok(scriptedClasses(html).has('reveal'), 'a class only the inline script names is visible');
  assert.ok(idsIn(html).includes('onthispage'), 'the section index\'s own id is visible');
});
