#!/bin/bash
# PreToolUse(Edit|Write|NotebookEdit). Files that have a generator, edited only
# through the generator.
#
# Each of these has already cost something. app/vendor/ is re-fetched and
# byte-diffed by a CI job precisely because editing it by hand is tempting; the
# six chart pages are the live "care needed" clause in the open TICKETS entry
# about the trust line -- fix them by hand and the next `npm run charts` throws
# the fix away, silently, with a green suite.
set -uo pipefail

# FAIL CLOSED. Without jq the reads below return empty, every pattern misses,
# and the hook allows everything while still reporting success -- the exact
# shape of false green this repo has been bitten by most. Exit 2 blocks the
# call instead. The check uses only bash builtins so it still works when the
# PATH is the thing that is broken.
if ! command -v jq >/dev/null 2>&1; then
  echo "guard-edit.sh cannot run: jq is not on PATH, so it cannot read the tool input. Failing closed rather than waving the call through." >&2
  exit 2
fi

path=$(jq -r '.tool_input.file_path // ""')

deny() {
  jq -n --arg r "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $r
    }
  }'
  exit 0
}

case "$path" in
  */app/vendor/*)
    deny 'Blocked: third-party code changes only through app/vendor/fetch.sh. The vendor-drift CI job re-runs that script and fails if the tree differs by a byte, so a hand edit here is a red build later rather than a fix now. Change the pin in fetch.sh and re-run it. AGENTS.md, "Rules".'
    ;;
  */scripts/budgets.json)
    deny 'Blocked: scripts/budgets.json is a RECORDED baseline, not a hand-authored file, and `requests` in it is a hand-set pin. Widen the ceiling in scripts/budgets.mjs instead, deliberately, and say why in the commit. AGENTS.md, "Layout".'
    ;;
esac

case "$path" in
  */app/*-player-basketball-rotation-chart.html)
    deny 'Blocked: the six roster-size chart pages are GENERATED by scripts/charts.mjs. An edit here survives until the next `npm run charts` and then vanishes with the suite still green -- which is the exact failure the open TICKETS entry on the trust line warns about. Edit scripts/charts.mjs and regenerate.'
    ;;
esac

exit 0
