/* The Benchcard mark (#284, after #277): a tilted card of three player-colored
   bars on the brand orange. This is the one place its geometry lives. The icon PNGs
   and the share image (scripts/og.mjs), the chart pages (scripts/charts.mjs) and
   the static copies in index.html, about.html and advanced.html all take
   their markup from `markSvg`; test/mark-drift.test.js holds the static copies
   equal to it. The hues are fixed on purpose: they were picked for the mark,
   not read from the app's runtime player palette. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const GROUND = '#D2500A';
const CARD = '#F4F4F6';
const HUES = ['#C0504D', '#C9762F', '#2E8A7A'];
/* start%-end% of the row width, per row */
const STINTS = [[[0, 70]], [[30, 100]], [[0, 45], [70, 100]]];
const ROW_X = 26, ROW_Y = 24, ROW_W = 48, ROW_H = 11, ROW_STEP = 20; // 11 tall + a 9 gap
const CARD_RECT = [17, 10, 66, 80, 9]; // x, y, width, height, rx
const PIVOT = [50, 50];

const n = v => +v.toFixed(4);

/* The bars, in paint order (each row's stints), as
   [x, y, width, height, rx, fill] in the 100-unit square, before the tilt. */
const rowBars = () => STINTS.flatMap((stints, i) => stints.map(([a, b]) =>
  [n(ROW_X + ROW_W * a / 100), ROW_Y + ROW_STEP * i, n(ROW_W * (b - a) / 100), ROW_H, ROW_H / 2, HUES[i]]));

/* Options: `shadow` adds the card's drop shadow (the tab icon and the header
   logo go without it, where it only muddies 16 and 26 pixels); `rounded`
   rounds the ground's corners instead of bleeding square; `scale` shrinks the
   card about the icon's center, so an install icon can keep the card and its
   shadow inside the maskable safe circle; `ariaHidden` marks a decorative
   logo; `ground` is the ground's fill and `card` the card's (the welcome logo passes
   var(--tint) and var(--tint-ink), so it follows the team color and the card
   keeps reading on it; everything else keeps the brand orange and paper). */
export function markSvg(size, { shadow = false, rounded = false, scale = 1, ariaHidden = false, ground = GROUND, card = CARD } = {}) {
  const [cx, cy, cw, ch, crx] = CARD_RECT;
  const rows = rowBars()
    .map(([x, y, w, h, rx, fill]) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}"/>`)
    .join('');
  const fit = scale === 1 ? '' : `translate(50 50) scale(${scale}) translate(-50 -50) `;
  const filter = shadow
    ? '<defs><filter id="mark-shadow" x="-30%" y="-30%" width="160%" height="160%">'
      + '<feDropShadow dx="0" dy="2" stdDeviation="2.2" flood-color="#000" flood-opacity=".28"/></filter></defs>'
    : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 100 100"${ariaHidden ? ' aria-hidden="true"' : ''}>`
    + filter
    + `<rect width="100" height="100"${rounded ? ' rx="22"' : ''} fill="${ground}"/>`
    + `<g transform="${fit}rotate(-8 ${PIVOT.join(' ')})">`
    + `<rect x="${cx}" y="${cy}" width="${cw}" height="${ch}" rx="${crx}" fill="${card}"${shadow ? ' filter="url(#mark-shadow)"' : ''}/>${rows}</g></svg>`;
}

/* The tab icon: the mark as a data URI, so a page costs no icon request
   (test/favicon.test.js). Rounded, no shadow. */
export const faviconHref = () => 'data:image/svg+xml,' + encodeURIComponent(markSvg(32, { rounded: true }));

/* The 26px logo beside "Benchcard" in a page header. Decorative, so hidden. */
export const logoSvg = opts => markSvg(26, { rounded: true, ariaHidden: true, ...opts });

/* The welcome logo: the same mark, its ground the live team tint (#244). The
   card is --mark-card: paper where paper reads on the tint (3:1), else the
   tint's ink (tokens.css) -- in dark Graphite the tint is the paper color
   itself, and a paper card would vanish into it. */
export const welcomeLogoSvg = () => logoSvg({ ground: 'var(--tint)', card: 'var(--mark-card)' }).replace(' aria-hidden="true"', '');

/* app/share.js paints the mark onto a canvas, synchronously (an image decode
   would cost the tap its activation, see the note there), and app/ cannot
   import from scripts/. So share.js holds a literal copy of the shapes, between
   two marker comments, and this is the text that belongs between them. */
export const SHARE_BEGIN = '/* mark:begin -- generated by scripts/mark.mjs, do not edit */';
export const SHARE_END = '/* mark:end */';
export const shareShapesSource = () => [
  SHARE_BEGIN,
  `const MARK_GROUND = '${GROUND}';`,
  `const MARK_TILT = [-8, ${PIVOT.join(', ')}];   // degrees, then the pivot`,
  `const MARK_SHAPES = [   // the card, then each bar: x, y, width, height, rx, fill`,
  ...[[...CARD_RECT, CARD], ...rowBars()].map(r => `  ${JSON.stringify(r)},`),
  '];',
  SHARE_END,
].join('\n');

/* The hand-kept files hold literal copies of the above. `node
   scripts/mark.mjs` rewrites them; `--check` exits 1 if one is stale. The six
   chart pages are not here: scripts/charts.mjs renders them from the same
   two functions. */
const STATIC = ['index.html', 'about.html', 'advanced.html', 'share.js'];
const escapeRe = text => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const between = new RegExp(`${escapeRe(SHARE_BEGIN)}[\\s\\S]*?${escapeRe(SHARE_END)}`);
const rewrite = html => html
  .replace(between, () => shareShapesSource())
  .replace(/(<link rel="icon" href=")[^"]*(")/, (_, a, b) => a + faviconHref() + b)
  .replace(/(<span class="wel-mark" aria-hidden="true">\s*)<svg[\s\S]*?<\/svg>/,
    (_, a) => a + welcomeLogoSvg())
  .replace(/(<a class="mark"[^>]*>\s*)<svg[\s\S]*?<\/svg>/, (_, a) => a + logoSvg());

if (import.meta.url === `file://${process.argv[1]}`) {
  const app = join(dirname(fileURLToPath(import.meta.url)), '..', 'app');
  const check = process.argv.includes('--check');
  const stale = [];
  for (const name of STATIC) {
    const path = join(app, name), cur = readFileSync(path, 'utf8'), next = rewrite(cur);
    if (cur === next) continue;
    stale.push(name);
    if (!check) writeFileSync(path, next);
  }
  console.log(stale.length ? `${check ? 'stale' : 'wrote'}: ${stale.join(', ')}` : 'up to date');
  process.exit(check && stale.length ? 1 : 0);
}
